language: c

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls

script:
  - make && ./hello

after_success:
  - coveralls --dryrun --exclude lib --exclude tests --gcov-options '\-lp'

